# Generated by Django 3.1.4 on 2021-03-15 21:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.BinaryField(default=0)),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(default=datetime.datetime.now)),
                ('endTime', models.DateTimeField(default=datetime.datetime.now)),
                ('roomNumber', models.IntegerField(default=201)),
                ('companionship', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TrcDetails.person')),
            ],
        ),
    ]
