# Generated by Django 3.1.4 on 2021-03-15 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrcDetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impression', models.CharField(max_length=300)),
                ('feltSpirit', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='actor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='actor', to='TrcDetails.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee', to='TrcDetails.person'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Companionship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juniorCompanion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_two', to='TrcDetails.person')),
                ('seniorCompanion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_one', to='TrcDetails.person')),
                ('trioComp', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_three', to='TrcDetails.person')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='survey',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='TrcDetails.survey'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='companionship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TrcDetails.companionship'),
        ),
    ]
