# Generated by Django 3.1.4 on 2021-03-15 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrcDetails', '0002_auto_20210315_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companionship',
            name='trioComp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_three', to='TrcDetails.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
