# Generated by Django 3.1.4 on 2021-03-15 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrcDetails', '0003_auto_20210315_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companionship',
            name='trioComp',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TrcDetails.survey'),
        ),
    ]
